pipeline {
    agent any  // Use any available agent

    environment {
        DOTNET_CLI_HOME = 'C:\\Temp'  // Prevents permission issues in Windows
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/khushaliporwal/TaskManagement'
            }
        }

        stage('Restore Dependencies') {
            steps {
                bat 'dotnet restore TaskManagementAPI/TaskManagementAPI.sln'
            }
        }

        stage('Build') {
            steps {
                bat 'dotnet build TaskManagementAPI/TaskManagementAPI.sln --configuration Release'
            }
        }

        stage('Test') {
            steps {
                bat 'dotnet test TaskManagementAPI/TaskManagementAPI.sln --configuration Release'
            }
        }

        stage('Publish') {
            steps {
                bat 'rmdir /S /Q publish || echo "No existing publish directory"'
                bat 'dotnet publish TaskManagementAPI/TaskManagementAPI.sln --configuration Release --output ./publish'
            }
        }
    }

    post {

        success {
            echo 'Build succeeded!'
        }

        failure {
            echo 'Build failed!'
        }
    }
}
