name: .NET Core CI

on:
  push:
    branches:
      - main  # Trigger CI on push to the main branch
  pull_request:
    branches:
      - main  # Trigger CI on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the build on the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Step to checkout code

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Ensure to use .NET 6 SDK

    - name: Restore dependencies
      run: dotnet restore ./TaskManagementAPI/TaskManagementAPI.csproj  # Path to your csproj file

    - name: Build the solution
      run: dotnet build ./TaskManagementAPI/TaskManagementAPI.csproj --configuration Release  # Path to your csproj file

    - name: Run tests
      run: dotnet test ./TaskManagementAPI/TaskManagementAPI.csproj  # Path to your csproj file

    - name: Publish the application
      run: dotnet publish ./TaskManagementAPI/TaskManagementAPI.csproj --configuration Release --output ./publish  # Publish to a folder
