name: .NET Core CI/CD

on:
  push:
    branches:
      - main  # Trigger CI/CD on push to main
  pull_request:
    branches:
      - main  # Trigger CI/CD on pull request to main

jobs:
  build:
    runs-on: ubuntu-latest  # Use latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0'  # Ensure to use .NET 6 SDK

    - name: Restore dependencies
      run: dotnet restore ./TaskManagementAPI/TaskManagementAPI.csproj

    - name: Build the solution
      run: dotnet build ./TaskManagementAPI/TaskManagementAPI.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./TaskManagementAPI/TaskManagementAPI.csproj --no-restore --verbosity normal

    - name: Publish the application
      run: |
        mkdir -p ./publish
        dotnet publish ./TaskManagementAPI/TaskManagementAPI.csproj --configuration Release --output ./publish
        ls -la ./publish  # Debugging step to verify publish folder exists

    - name: Archive artifact
      uses: actions/upload-artifact@v4  # Updated to latest version
      with:
        name: published-app
        path: ./publish

  deploy:
    needs: build  # Run deployment only if build succeeds
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Download artifact
      uses: actions/download-artifact@v4  # Updated to latest version
      with:
        name: published-app
        path: ./publish

    - name: Install or Update AWS CLI
      run: |
        if aws --version &> /dev/null; then
          echo "AWS CLI already installed. Updating..."
          pip3 install --upgrade --user awscli
        else
          echo "AWS CLI not found. Installing..."
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install awscli --user
        fi
        echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc
        aws --version
        
    - name: Install Elastic Beanstalk CLI
      run: pip install --user awsebcli --upgrade

    - name: Create Deployment Package
      run: |
        cd publish
        zip -r ../deploy.zip .
        cd ..
        ls -lah deploy.zip  # Debugging step

    - name: Deploy to AWS Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
        EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
      run: |
        echo "Uploading deploy.zip to S3..."
        aws s3 cp deploy.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-490004655906/deploy.zip

        echo "Creating new application version in Elastic Beanstalk..."
        aws elasticbeanstalk create-application-version --application-name "$EB_APPLICATION_NAME" --version-label "v${{ github.run_number }}" --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-490004655906",S3Key="deploy.zip"

        echo "Deploying new version to Elastic Beanstalk..."
        aws elasticbeanstalk update-environment --application-name "$EB_APPLICATION_NAME" --environment-name "$EB_ENVIRONMENT_NAME" --version-label "v${{ github.run_number }}"
