name: .NET Core CI

on:
  push:
    branches:
      - main  # Trigger CI on push to the main branch
  pull_request:
    branches:
      - main  # Trigger CI on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the build on the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Step to checkout code

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Ensure to use .NET 6 SDK

    - name: Restore dependencies
      run: dotnet restore  # Restore NuGet packages

    - name: Build the solution
      run: dotnet build --configuration Release  # Build the project in Release mode

    - name: Run tests
      run: dotnet test  # Run the unit tests

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish  # Publish to a folder
